project_name: tokeny
version: 2

builds:
  - # macOS
    id: darwin
    main: ./main.go
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
    ldflags:
      - -s -w
  - # Linux
    id: linux
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
homebrew_casks:
  - name: tokeny
    repository:
      owner: zalopay-oss
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url:
      template: "https://github.com/zalopay-oss/tokeny/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Tokeny's GitHubAction
      email: phuc.quang102@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/zalopay-oss/tokeny"
    description: "Minimal TOTP generator from your Shell"
archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else if eq .Os "linux" }}Linux{{ else }}{{ .Os }}{{ end }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}'
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^dev:'
      - 'README'
      - Merge pull request
      - Merge branch