project_name: tokeny

builds:
  - id: tokeny-darwin-amd64
    binary: tokeny
    env:
      - CGO_ENABLED=0
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    targets:
      - darwin_amd64
      - darwin_arm64
    ldflags:
      - -s -w
  - id: tokeny-linux-amd64
    binary: tokeny
    env:
      - CGO_ENABLED=0
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
archives:
  - replacements:
      amd64: x86_64
      darwin: macOS
      linux: Linux
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^dev:'
      - 'README'
      - Merge pull request
      - Merge branch