builds:
  - id: tokeny-darwin-amd64
    binary: tokeny
    env:
      - CGO_ENABLED=0
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64
  - id: tokeny-linux-amd64
    binary: tokeny
    env:
      - CGO_ENABLED=0
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
archives:
  - format: tar.gz
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      darwin: macOS
      linux: Linux
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^dev:'
      - 'README'
      - Merge pull request
      - Merge branch