project_name: tokeny

builds:
  - # macOS
    id: darwin
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    targets:
      - darwin_amd64
      - darwin_arm64
    ldflags:
      - -s -w
  - # Linux
    id: linux
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
brews:
  - name: tokeny
    tap:
      owner: zalopay-oss
      name: homebrew-tap
    url_template: "https://github.com/zalopay-oss/tokeny/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Tokeny's GitHubAction
      email: phuc.quang102@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/zalopay-oss/tokeny"
    description: "Minimal TOTP generator from your Shell"
archives:
  - replacements:
      amd64: x86_64
      darwin: macOS
      linux: Linux
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^dev:'
      - 'README'
      - Merge pull request
      - Merge branch